#!/bin/sh
set -eu

readonly_user="${FAKE_STORE_READONLY_USER:-sou2ai_store_reader}"
readonly_password="${FAKE_STORE_READONLY_PASSWORD:-sou2ai_store_reader_local}"
store_timezone="${FAKE_STORE_TIMEZONE:-Asia/Beirut}"
store_currency="${FAKE_STORE_CURRENCY:-LBP}"

psql --set=ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set=database_name="$POSTGRES_DB" \
  --set=readonly_user="$readonly_user" \
  --set=readonly_password="$readonly_password" \
  --set=store_timezone="$store_timezone" \
  --set=store_currency="$store_currency" <<'SQL'
SELECT format(
    'CREATE ROLE %I LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD %L',
    :'readonly_user', :'readonly_password'
)
WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = :'readonly_user')\gexec
SELECT format(
    'ALTER ROLE %I LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD %L',
    :'readonly_user', :'readonly_password'
)\gexec
SELECT format('ALTER ROLE %I IN DATABASE %I SET default_transaction_read_only = on',
              :'readonly_user', :'database_name')\gexec
SELECT format('ALTER ROLE %I IN DATABASE %I SET statement_timeout = %L',
              :'readonly_user', :'database_name', '2000ms')\gexec

SELECT format('REVOKE ALL ON DATABASE %I FROM PUBLIC', :'database_name')\gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO %I',
              :'database_name', :'readonly_user')\gexec
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

CREATE SCHEMA IF NOT EXISTS minimarket AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS private_internal AUTHORIZATION CURRENT_USER;
REVOKE ALL ON SCHEMA minimarket, private_internal FROM PUBLIC;

CREATE TABLE IF NOT EXISTS minimarket.store_configuration (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    business_timezone text NOT NULL,
    currency_code varchar(3) NOT NULL CHECK (currency_code ~ '^[A-Z]{3}$'),
    data_updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS minimarket.categories (
    category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS minimarket.catalog_items (
    item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code text NOT NULL UNIQUE,
    merchant_sku text UNIQUE,
    ean_barcode text UNIQUE,
    display_label text NOT NULL,
    category_id integer REFERENCES minimarket.categories(category_id),
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS minimarket.stock_locations (
    location_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_code text NOT NULL UNIQUE,
    location_label text NOT NULL,
    location_type text NOT NULL CHECK (location_type IN ('BRANCH', 'WAREHOUSE'))
);

CREATE TABLE IF NOT EXISTS minimarket.stock_levels (
    location_id integer NOT NULL REFERENCES minimarket.stock_locations(location_id),
    item_id integer NOT NULL REFERENCES minimarket.catalog_items(item_id),
    physical_quantity numeric(12, 3) NOT NULL CHECK (physical_quantity >= 0),
    reorder_threshold numeric(12, 3) NOT NULL CHECK (reorder_threshold >= 0),
    desired_quantity numeric(12, 3) NOT NULL CHECK (
        desired_quantity >= reorder_threshold
    ),
    changed_at timestamptz NOT NULL,
    PRIMARY KEY (location_id, item_id)
);

CREATE TABLE IF NOT EXISTS minimarket.stock_reservations (
    reservation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id integer NOT NULL,
    item_id integer NOT NULL,
    held_quantity numeric(12, 3) NOT NULL CHECK (held_quantity > 0),
    reservation_state text NOT NULL CHECK (
        reservation_state IN ('ACTIVE', 'RELEASED', 'FULFILLED', 'CANCELLED')
    ),
    expires_at timestamptz,
    created_at timestamptz NOT NULL,
    FOREIGN KEY (location_id, item_id)
        REFERENCES minimarket.stock_levels(location_id, item_id)
);

CREATE TABLE IF NOT EXISTS minimarket.receipts (
    receipt_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_number text NOT NULL UNIQUE,
    branch_location_id integer NOT NULL REFERENCES minimarket.stock_locations(location_id),
    receipt_state text NOT NULL CHECK (
        receipt_state IN ('COMPLETED', 'PENDING', 'CANCELLED', 'RETURNED')
    ),
    currency_code varchar(3) NOT NULL,
    completed_at timestamptz,
    created_at timestamptz NOT NULL,
    changed_at timestamptz NOT NULL,
    CHECK (
        (receipt_state IN ('COMPLETED', 'RETURNED') AND completed_at IS NOT NULL)
        OR (receipt_state IN ('PENDING', 'CANCELLED'))
    )
);

CREATE TABLE IF NOT EXISTS minimarket.receipt_lines (
    receipt_line_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id integer NOT NULL REFERENCES minimarket.receipts(receipt_id),
    item_id integer NOT NULL REFERENCES minimarket.catalog_items(item_id),
    sold_quantity numeric(12, 3) NOT NULL CHECK (sold_quantity > 0),
    unit_price numeric(14, 2) NOT NULL CHECK (unit_price >= 0),
    line_total numeric(14, 2) GENERATED ALWAYS AS (sold_quantity * unit_price) STORED
);

CREATE TABLE IF NOT EXISTS minimarket.refunds (
    refund_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_number text NOT NULL UNIQUE,
    receipt_id integer NOT NULL REFERENCES minimarket.receipts(receipt_id),
    refund_state text NOT NULL CHECK (
        refund_state IN ('COMPLETED', 'PENDING', 'CANCELLED')
    ),
    refunded_at timestamptz,
    created_at timestamptz NOT NULL,
    changed_at timestamptz NOT NULL,
    CHECK (
        (refund_state = 'COMPLETED' AND refunded_at IS NOT NULL)
        OR refund_state IN ('PENDING', 'CANCELLED')
    )
);

CREATE TABLE IF NOT EXISTS minimarket.refund_lines (
    refund_line_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id integer NOT NULL REFERENCES minimarket.refunds(refund_id),
    receipt_line_id integer NOT NULL REFERENCES minimarket.receipt_lines(receipt_line_id),
    returned_quantity numeric(12, 3) NOT NULL CHECK (returned_quantity > 0),
    refund_total numeric(14, 2) NOT NULL CHECK (refund_total >= 0)
);

CREATE TABLE IF NOT EXISTS private_internal.admin_notes (
    note_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note text NOT NULL
);

INSERT INTO minimarket.store_configuration (
    singleton, business_timezone, currency_code, data_updated_at
) VALUES (
    true, :'store_timezone', :'store_currency', TIMESTAMPTZ '2026-08-24 09:00:00+03'
) ON CONFLICT (singleton) DO UPDATE SET
    business_timezone = EXCLUDED.business_timezone,
    currency_code = EXCLUDED.currency_code,
    data_updated_at = EXCLUDED.data_updated_at;

INSERT INTO minimarket.categories (category_id, label) VALUES
    (1, 'Pantry'),
    (2, 'Dairy'),
    (3, 'Beverages'),
    (4, 'Snacks'),
    (5, 'Household')
ON CONFLICT (category_id) DO NOTHING;

INSERT INTO minimarket.catalog_items (
    item_id, item_code, merchant_sku, ean_barcode, display_label, category_id
) VALUES
    (1, 'P1001', 'RICE-5KG', '5280001000011', 'Cedars Long Grain Rice 5 kg', 1),
    (2, 'P1002', 'LABNEH-500', '5280001000028', 'Fresh Labneh 500 g', 2),
    (3, 'P1003', 'WATER-1500', '5280001000035', 'Nestle Pure Life Water 1.5 L', 3),
    (4, 'P1004', 'CHIPS-SALT-170', '5280001000042', 'Master Chips Salt 170 g', 4),
    (5, 'P1005', 'TISSUE-6', '5280001000059', 'Fine Tissue 6 Rolls', 5),
    (6, 'P1006', 'ZAATAR-500', '5280001000066', 'Lebanese Zaatar 500 g', 1)
ON CONFLICT (item_id) DO NOTHING;

INSERT INTO minimarket.stock_locations (
    location_id, location_code, location_label, location_type
) VALUES
    (1, 'BR-BEY', 'Achrafieh Branch', 'BRANCH'),
    (2, 'BR-JBEIL', 'Jbeil Branch', 'BRANCH'),
    (3, 'WH-BEY', 'Beirut Central Warehouse', 'WAREHOUSE')
ON CONFLICT (location_id) DO NOTHING;

INSERT INTO minimarket.stock_levels (
    location_id, item_id, physical_quantity, reorder_threshold,
    desired_quantity, changed_at
) VALUES
    (1, 1, 12, 10, 30, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (1, 2, 8, 6, 18, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (1, 3, 40, 20, 50, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (1, 4, 15, 15, 40, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (1, 5, 4, 5, 15, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (1, 6, 20, 8, 24, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (2, 1, 25, 10, 30, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (2, 2, 5, 6, 18, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (2, 3, 12, 20, 50, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (2, 4, 50, 15, 40, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (2, 5, 10, 5, 15, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (2, 6, 7, 8, 24, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (3, 1, 100, 40, 150, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (3, 2, 30, 15, 50, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (3, 3, 200, 80, 300, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (3, 4, 80, 30, 120, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (3, 5, 40, 15, 60, TIMESTAMPTZ '2026-08-24 09:00:00+03'),
    (3, 6, 35, 12, 50, TIMESTAMPTZ '2026-08-24 09:00:00+03')
ON CONFLICT (location_id, item_id) DO NOTHING;

INSERT INTO minimarket.stock_reservations (
    reservation_id, location_id, item_id, held_quantity, reservation_state,
    expires_at, created_at
) VALUES
    (1, 1, 1, 3, 'ACTIVE', TIMESTAMPTZ '2030-01-01 00:00:00+02', TIMESTAMPTZ '2026-08-24 08:00:00+03'),
    (2, 1, 1, 2, 'RELEASED', NULL, TIMESTAMPTZ '2026-08-23 08:00:00+03'),
    (3, 1, 2, 2, 'ACTIVE', NULL, TIMESTAMPTZ '2026-08-24 08:05:00+03'),
    (4, 1, 3, 7, 'ACTIVE', TIMESTAMPTZ '2026-01-01 00:00:00+02', TIMESTAMPTZ '2025-12-31 08:00:00+02'),
    (5, 1, 3, 5, 'ACTIVE', TIMESTAMPTZ '2030-01-01 00:00:00+02', TIMESTAMPTZ '2026-08-24 08:10:00+03'),
    (6, 2, 1, 1, 'ACTIVE', NULL, TIMESTAMPTZ '2026-08-24 08:15:00+03'),
    (7, 2, 3, 2, 'ACTIVE', NULL, TIMESTAMPTZ '2026-08-24 08:20:00+03'),
    (8, 3, 1, 10, 'ACTIVE', NULL, TIMESTAMPTZ '2026-08-24 08:25:00+03'),
    (9, 3, 3, 20, 'ACTIVE', NULL, TIMESTAMPTZ '2026-08-24 08:30:00+03')
ON CONFLICT (reservation_id) DO NOTHING;

INSERT INTO minimarket.receipts (
    receipt_id, receipt_number, branch_location_id, receipt_state,
    currency_code, completed_at, created_at, changed_at
) VALUES
    (1, 'R-1001', 1, 'COMPLETED', :'store_currency', TIMESTAMPTZ '2026-08-20 10:00:00+03', TIMESTAMPTZ '2026-08-20 10:00:00+03', TIMESTAMPTZ '2026-08-20 10:00:00+03'),
    (2, 'R-1002', 1, 'COMPLETED', :'store_currency', TIMESTAMPTZ '2026-08-20 23:30:00+03', TIMESTAMPTZ '2026-08-20 23:30:00+03', TIMESTAMPTZ '2026-08-20 23:30:00+03'),
    (3, 'R-1003', 2, 'COMPLETED', :'store_currency', TIMESTAMPTZ '2026-08-21 09:00:00+03', TIMESTAMPTZ '2026-08-21 09:00:00+03', TIMESTAMPTZ '2026-08-21 09:00:00+03'),
    (4, 'R-1004', 1, 'PENDING', :'store_currency', NULL, TIMESTAMPTZ '2026-08-21 12:00:00+03', TIMESTAMPTZ '2026-08-21 12:00:00+03'),
    (5, 'R-1005', 1, 'CANCELLED', :'store_currency', NULL, TIMESTAMPTZ '2026-08-21 13:00:00+03', TIMESTAMPTZ '2026-08-21 13:30:00+03'),
    (6, 'R-1006', 1, 'RETURNED', :'store_currency', TIMESTAMPTZ '2026-08-21 14:00:00+03', TIMESTAMPTZ '2026-08-21 14:00:00+03', TIMESTAMPTZ '2026-08-22 10:00:00+03'),
    (7, 'R-1007', 2, 'COMPLETED', :'store_currency', TIMESTAMPTZ '2026-08-22 00:00:00+03', TIMESTAMPTZ '2026-08-22 00:00:00+03', TIMESTAMPTZ '2026-08-22 00:00:00+03'),
    (8, 'R-1008', 1, 'COMPLETED', :'store_currency', TIMESTAMPTZ '2026-08-19 23:59:00+03', TIMESTAMPTZ '2026-08-19 23:59:00+03', TIMESTAMPTZ '2026-08-19 23:59:00+03'),
    (9, 'R-1009', 1, 'COMPLETED', :'store_currency', TIMESTAMPTZ '2026-08-22 15:00:00+03', TIMESTAMPTZ '2026-08-22 15:00:00+03', TIMESTAMPTZ '2026-08-22 16:00:00+03')
ON CONFLICT (receipt_id) DO NOTHING;

INSERT INTO minimarket.receipt_lines (
    receipt_line_id, receipt_id, item_id, sold_quantity, unit_price
) VALUES
    (1, 1, 1, 2, 500000),
    (2, 1, 3, 3, 40000),
    (3, 2, 2, 4, 180000),
    (4, 2, 4, 3, 100000),
    (5, 3, 3, 6, 40000),
    (6, 3, 6, 3, 500000),
    (7, 4, 1, 10, 500000),
    (8, 5, 1, 20, 500000),
    (9, 6, 5, 2, 250000),
    (10, 7, 1, 1, 500000),
    (11, 7, 4, 2, 100000),
    (12, 8, 3, 2, 40000),
    (13, 9, 2, 2, 180000)
ON CONFLICT (receipt_line_id) DO NOTHING;

INSERT INTO minimarket.refunds (
    refund_id, refund_number, receipt_id, refund_state,
    refunded_at, created_at, changed_at
) VALUES
    (1, 'RF-1001', 6, 'COMPLETED', TIMESTAMPTZ '2026-08-22 10:00:00+03', TIMESTAMPTZ '2026-08-22 10:00:00+03', TIMESTAMPTZ '2026-08-22 10:00:00+03'),
    (2, 'RF-1002', 9, 'COMPLETED', TIMESTAMPTZ '2026-08-22 16:00:00+03', TIMESTAMPTZ '2026-08-22 16:00:00+03', TIMESTAMPTZ '2026-08-22 16:00:00+03'),
    (3, 'RF-1003', 2, 'PENDING', NULL, TIMESTAMPTZ '2026-08-22 17:00:00+03', TIMESTAMPTZ '2026-08-22 17:00:00+03'),
    (4, 'RF-1004', 1, 'CANCELLED', NULL, TIMESTAMPTZ '2026-08-22 18:00:00+03', TIMESTAMPTZ '2026-08-22 18:00:00+03')
ON CONFLICT (refund_id) DO NOTHING;

INSERT INTO minimarket.refund_lines (
    refund_line_id, refund_id, receipt_line_id, returned_quantity, refund_total
) VALUES
    (1, 1, 9, 2, 500000),
    (2, 2, 13, 1, 180000),
    (3, 3, 3, 1, 180000),
    (4, 4, 1, 1, 500000)
ON CONFLICT (refund_line_id) DO NOTHING;

INSERT INTO private_internal.admin_notes (note_id, note)
VALUES (1, 'Not exposed to the Sou2AI read-only adapter.')
ON CONFLICT (note_id) DO NOTHING;

REVOKE ALL ON ALL TABLES IN SCHEMA minimarket, private_internal FROM PUBLIC;
SELECT format('REVOKE ALL ON ALL TABLES IN SCHEMA minimarket FROM %I',
              :'readonly_user')\gexec
SELECT format('REVOKE ALL ON SCHEMA private_internal FROM %I', :'readonly_user')\gexec
SELECT format('GRANT USAGE ON SCHEMA minimarket TO %I', :'readonly_user')\gexec
SELECT format(
    'GRANT SELECT ON TABLE minimarket.store_configuration, minimarket.categories, minimarket.catalog_items, minimarket.stock_locations, minimarket.stock_levels, minimarket.stock_reservations, minimarket.receipts, minimarket.receipt_lines, minimarket.refunds, minimarket.refund_lines TO %I',
    :'readonly_user'
)\gexec
ALTER DEFAULT PRIVILEGES IN SCHEMA minimarket REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA private_internal REVOKE ALL ON TABLES FROM PUBLIC;
SQL
